// USER
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";


//UNIT
export const CREATE_UNIT = "CREATE_UNIT";
export const CREATE_UNIT_SUCCESS = "CREATE_UNIT_SUCCESS";
export const CREATE_UNIT_FAILURE = "CREATE_UNIT_FAILURE";

export const FETCH_UNITS = "FETCH_UNITS";
export const FETCH_UNITS_SUCCESS = "FETCH_UNITS_SUCCESS";
export const FETCH_UNITS_FAILURE = "FETCH_UNITS_FAILURE";

export const FETCH_UNITS_ACTIVE = "FETCH_UNITS_ACTIVE";
export const FETCH_UNITS_ACTIVE_SUCCESS = "FETCH_UNITS_ACTIVE_SUCCESS";
export const FETCH_UNITS_ACTIVE_FAILURE = "FETCH_UNITS_ACTIVE_FAILURE";

export const FETCH_UNIT = "FETCH_UNIT";
export const FETCH_UNIT_SUCCESS = "FETCH_UNIT_SUCCESS";
export const FETCH_UNIT_FAILURE = "FETCH_UNIT_FAILURE";

export const UPDATE_UNIT = "UPDATE_UNIT";
export const UPDATE_UNIT_SUCCESS = "UPDATE_UNIT_SUCCESS";
export const UPDATE_UNIT_FAILURE = "UPDATE_UNIT_FAILURE";

export const DELETE_UNIT = "DELETE_UNIT";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_FAILURE = "DELETE_UNIT_FAILURE";

// LESSON
export const CREATE_LESSON = "CREATE_LESSON";
export const CREATE_LESSON_SUCCESS = "CREATE_LESSON_SUCCESS";
export const CREATE_LESSON_FAILURE = "CREATE_LESSON_FAILURE";

export const FETCH_LESSONS = "FETCH_LESSONS";
export const FETCH_LESSONS_SUCCESS = "FETCH_LESSONS_SUCCESS";
export const FETCH_LESSONS_FAILURE = "FETCH_LESSONS_FAILURE";

export const FETCH_LESSON = "FETCH_LESSON";
export const FETCH_LESSON_SUCCESS = "FETCH_LESSON_SUCCESS";
export const FETCH_LESSON_FAILURE = "FETCH_LESSON_FAILURE";

export const UPDATE_LESSON = "UPDATE_LESSON";
export const UPDATE_LESSON_SUCCESS = "UPDATE_LESSON_SUCCESS";
export const UPDATE_LESSON_FAILURE = "UPDATE_LESSON_FAILURE";

export const DELETE_LESSON = "DELETE_LESSON";
export const DELETE_LESSON_SUCCESS = "DELETE_LESSON_SUCCESS";
export const DELETE_LESSON_FAILURE = "DELETE_LESSON_FAILURE";

